### ISSUE TITLE
switch logger off

### ISSUE THREAD

**Issue by omarazmi** [dbfannin/ng2-logger#1]
how i can switch logger off programmatically either console logging or api logs ?

**Comment by omarazmi** [comment]
Thanks, 
if i pass any other parameter not in levels enum 
`enum Levels {
  'TRACE',
  'DEBUG',
  'INFO',
  'LOG',
  'WARN',
  'ERROR'
}
`

then the logger will be OFF.

**Comment by dbfannin** [comment]
I've pushed a new update which handles the "OFF" scenario, and updated the documentation. Hope this helps!
